"""create pantryitem table.

Revision ID: 7d311ae8966a
Revises: 0001_create_user
Create Date: 2026-09-13 17:50:51.755826
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision: str = '7d311ae8966a'
down_revision: Union[str, None] = '0001_create_user'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantryitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ingrediente', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fecha_caducidad', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pantryitem_usuario_id'), 'pantryitem', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pantryitem_usuario_id'), table_name='pantryitem')
    op.drop_table('pantryitem')
    # ### end Alembic commands ###